main: com.drain.MCWebSocketPlugin.MCWebSocketPlugin
name: MCWebSocketPlugin
version: 1.0
author: drain
description: "Platform for building websocket-based integrations for Minecraft"
api-version: 1.16
commands:
    mcws-reload:
        description: Reload the configuration for MCWebSocket
        usage: /mcws-reload
        permission: mcws.reload
    mcws-addclient:
        description: Creates a new MCWS client
        usage: /mcws-addclient <client name> <access level>
        permission: mcws.addclient
    mcws-status:
        description: Lists clients currently connected to the server through MCWS
        usage: /mcws-status
        permission: mcws.status