main: com.drain.MCWebSocketPlugin.MCWebSocketPlugin
name: MCWebSocketPlugin
version: 1.0
author: drain
description: "Plugin that allows clients to listen in on server events via WebSocket"
api-version: 1.16
commands:
    mcws-reload:
        description: Reload the configuration for MCWebSocket
        usage: /mcws-reload
        permission: mcws.reload
    mcws-addclient:
        description: Creates a new MCWS client
        usage: /mcws-addclient <client name> <access level>
        permission: mcws.addclient